function [newInstructions,betweenInstructions,endStructions] = getAttentionInstructions(keys)
  % set the instructions (in their own function for easy tracking/editing
  % with git
  % each element of a cell is a new screen
  %
  pushinstructions = [...
      'Push your ' keys{1} ' if the target direction is left.\n\n'...
      'Push your ' keys{2} ' if right is the target direction.'...
      ];
  
  newInstructions = { ...
        'Welcome to the Attention Game!\n', ...
        [ ...
         'To play this game,\n' ...
         'you will push the left or right key\n'...
         'based on what direction a specific ring opens.' ...
        ],...
        [ ...
          'Step 1\n',...
          'A colored circle will be in the center of the screen.\n',...
          'This color is the target color\n'...
        ],...
        @(w) drawRing(w,'noload','Fill','Position',1,'Color',1),...
        'In this example, the target color is orange\n\n', ...
        [...
          'Step 2\n'...
          'Six rings will appear.\n',...
          'You care about the one that is the target color.\n', ...
          'This is the target ring. '...
        ],...
        @(w) drawRing(w, 'Position', 1:6, 'Color',[1 5 5 5 5 5]), ...
        'In this example, the target ring is in the top left\n\n', ...
        [...
          'Step 3\n'...
          'The rings will open up.\n'...
          'They will all be missing part of the left or right side.\n'...
          'The target direction is what side of the target ring is open.\n'...
        ],...
        @(w) drawRing(w,'PROBE', 'Position', 1:6, 'Color',[1 5 5 5 5 5],'Directions',[1 2 2 2 2 2]), ...
        [...
          'Step 4\n\n'...
          pushinstructions ...
          '\n\nIn this example, you should push ' keys{2} '\n\n' ...
        ], ....
        [...
          'Sometimes trials will end early\n\n', ...
          'When you see a new target color, forget the old color\n',...
          'and get ready to look for a new target ring.'...
        ], ...
        [...
         'Remember:\n\n' ...
         'It is important for us that your gaze always stays at the center of the screen\n'...
        ]...

        };
    betweenInstructions = { [ 'Welcome Back\n\n' pushinstructions ] };
    endStructions       = {'Thanks For Playing'};
    
end